### PR TITLE
fixed #5763,fixed #5760 : Add utils.securopen func to fix not syscall.O_NOFOLLOW on Windows

### LINKED ISSUE #5760: v2.3.6 on windows 11报错
>PS E:\src\hello> go  build
># github.com/beego/beego/v2/core/config
>C:\Users\hetao\go\pkg\mod\github.com\beego\beego\v2@v2.3.6\core\config\ini.go:350:64: undefined: syscall.O_NOFOLLOW
># github.com/beego/beego/v2/core/admin
>C:\Users\hetao\go\pkg\mod\github.com\beego\beego\v2@v2.3.6\core\admin\profile.go:69:64: undefined: syscall.O_NOFOLLOW
>C:\Users\hetao\go\pkg\mod\github.com\beego\beego\v2@v2.3.6\core\admin\profile.go:87:64: undefined: syscall.O_NOFOLLOW
># github.com/beego/beego/v2/server/web/session
>C:\Users\hetao\go\pkg\mod\github.com\beego\beego\v2@v2.3.6\server\web\session\sess_file.go:103:122: undefined: syscall.O_NOFOLLOW
>C:\Users\hetao\go\pkg\mod\github.com\beego\beego\v2@v2.3.6\server\web\session\sess_file.go:109:144: undefined: syscall.O_NOFOLLOW
>C:\Users\hetao\go\pkg\mod\github.com\beego\beego\v2@v2.3.6\server\web\session\sess_file.go:167:63: undefined: syscall.O_NOFOLLOW
>C:\Users\hetao\go\pkg\mod\github.com\beego\beego\v2@v2.3.6\server\web\session\sess_file.go:292:69: undefined: syscall.O_NOFOLLOW

换成2.3.5就是正常的，linux也正常

### LINKED ISSUE #5763: MacOs下beego v2.3.6交叉编译出现错误
```bash
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o mooc.exe main.go
# github.com/beego/beego/v2/core/config
/Users/zhushuyan/go/pkg/mod/github.com/beego/beego/v2@v2.3.6/core/config/ini.go:350:64: undefined: syscall.O_NOFOLLOW
# github.com/beego/beego/v2/core/admin
/Users/zhushuyan/go/pkg/mod/github.com/beego/beego/v2@v2.3.6/core/admin/profile.go:69:64: undefined: syscall.O_NOFOLLOW
/Users/zhushuyan/go/pkg/mod/github.com/beego/beego/v2@v2.3.6/core/admin/profile.go:87:64: undefined: syscall.O_NOFOLLOW
# github.com/beego/beego/v2/server/web/session
/Users/zhushuyan/go/pkg/mod/github.com/beego/beego/v2@v2.3.6/server/web/session/sess_file.go:103:122: undefined: syscall.O_NOFOLLOW
/Users/zhushuyan/go/pkg/mod/github.com/beego/beego/v2@v2.3.6/server/web/session/sess_file.go:109:144: undefined: syscall.O_NOFOLLOW
/Users/zhushuyan/go/pkg/mod/github.com/beego/beego/v2@v2.3.6/server/web/session/sess_file.go:167:63: undefined: syscall.O_NOFOLLOW
/Users/zhushuyan/go/pkg/mod/github.com/beego/beego/v2@v2.3.6/server/web/session/sess_file.go:292:69: undefined: syscall.O_NOFOLLOW
```

### PR DESCRIPTION
**Pull request by lengpucheng**
fixed https://github.com/beego/beego/issues/5760 ,fixed https://github.com/beego/beego/issues/5763 Add utils.securopen func
```go

// OpenFileSecure Secure file opening function
// Check whether it is a symbolic connection in Windows
func OpenFileSecure(name string, flag int, perm os.FileMode) (*os.File, error) {
	// Check if it's a symbolic link
	if fi, err := os.Lstat(name); err == nil {
		if isSymlink(fi) {
			return nil, &os.PathError{
				Op:   "open",
				Path: name,
				Err:  syscall.ERROR_ACCESS_DENIED,
			}
		}
	}
	// Open the file in the normal way
	return os.OpenFile(name, flag, perm)
}

// isSymlink Check if the file is a symbolic link
func isSymlink(fi os.FileInfo) bool {
	return fi.Mode()&os.ModeSymlink != 0
}
```

and build for system fix not syscall.O_NOFOLLOW on Windows

### CODE REVIEW

File: core/utils/secureopen.go [hunk 1]
```diff
@@ -0,0 +1,26 @@
+//go:build !windows
+// +build !windows
+
+/*
+--------------------------------------------------
```
Comment (flycash) [inline core/utils/secureopen.go:5]: import license, you can copy the license form other files

File: core/utils/secureopen.go [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+*/
+
+package utils
+
+import (
+	"os"
+	"syscall"
+)
+
+// OpenFileSecure 安全文件打开函数
```
Comment (flycash) [inline core/utils/secureopen.go:22]: using English, please check all comments

File: core/utils/secureopen_windows.go [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+			}
+		}
+	}
+	// 普通方式打开文件
+	return os.OpenFile(name, flag, perm)
+}
+
+// isSymlink 检查文件是否是符号链接
+func isSymlink(fi os.FileInfo) bool {
+	if runtime.GOOS == "windows" {
```
Comment (flycash) [inline core/utils/secureopen_windows.go:42]: you already use build:windows, so it must be "windows", right?

File: core/utils/secureopen.go (hunk 2 above)
Comment (lengpucheng) [reply core/utils/secureopen.go]: Thanks I will revise it to English

File: core/utils/secureopen.go (hunk 1 above)
Comment (lengpucheng) [reply core/utils/secureopen.go]: Tanks i will edit it

File: core/utils/secureopen_windows.go (hunk 3 above)
Comment (lengpucheng) [reply core/utils/secureopen_windows.go]: @flycash ok thanks, I've modified these codes as per the spec
